### ISSUE TITLE
What's your favorite half-finished tinkering? 

### ISSUE THREAD

**Issue by hampelm** [lmorchard/ama#3]

**Comment by lmorchard** [comment]
Right now, it's HTML5 game engine that I'm ill-advisedly building from scratch - aspirationally powering my entirely unfinished games [Parsec Patrol](https://lmorchard.github.io/parsec-patrol/sketches/steering/) and [Panic Ranger](https://lmorchard.github.io/panic-ranger/sketches/repulsors/).

In the past, I've also left unfinished projects for [web feed readers & processors](https://github.com/lmorchard?utf8=%E2%9C%93&tab=repositories&q=feed&type=&language=) and sometimes [EVE Online market tools](https://github.com/lmorchard?utf8=%E2%9C%93&tab=repositories&q=eve&type=&language=). I may resume any of them without warning. Or never look at them again.
