### ISSUE TITLE
Bitcoin

### ISSUE THREAD

**Issue by spencerhadley** [lmorchard/ama#5]
Where are you at with Bitcoin, smart contacts, and decentralized media like LBRY?

**Comment by lmorchard** [comment]
Hmm, only just now heard of LBRY. Looks interesting, maybe I'll carve out some time to learn more.

Do you mean smart contacts - or smart *contracts*? I've heard of those in relation to Bitcoin. Also interesting, but I've only heard enough to know the term but not enough to have an opinion. (If you *did* mean smart *contacts*, I don't know what that is.)

As for Bitcoin... My cynical take is it's a great system for folks who understand Bitcoin to profit from folks who don't understand Bitcoin. Also great for turning electricity into waste heat. 

Beyond that, I kind of hope it (or something like it) stabilizes and helps pay for the web via low to zero transaction cost micropayments. Though, it doesn't seem like it should scale very well, based on what I understand so far. That said, some smart people think it can scale, so it's possible I'm missing something.

**Comment by spencerhadley** [comment]
Thanks for your takes. Yeah, I meant smart contracts.
