### ISSUE TITLE
Investments

### ISSUE THREAD

**Issue by spencerhadley** [lmorchard/ama#6]
Small:  What do you invest in? How will you afford to be old and not work?

Big: How tied to society are you?

**Comment by lmorchard** [comment]
What we do is pretty boring: Live under our means. Put money in savings. Put money in a spread of boring investments. Hope to never retire. I might be surprised and find that I want to retire when I get older, though.

As for being tied to society - insofar as money is a consensual hallucination agreed to by society, we're pretty tied in and hope the money we're not spending gets honored in the long run. Aiming not to lean on society for support beyond that, though.
